= Powitanie, cel bloga

*Nie lubię pisać.*

To brzmi lepiej, niż standardowe "Witaj, świecie!" czy inne prymitywne posty, w których autor opisuje byle co, a i tak nikt tego nie czyta, czyż nie? Zdanie z nagłówka jest jednak prawdziwe - mimo że moje oceny z lekcji języka polskiego świadczą co innego, nie lubię pisać. Dlaczego? Bo za każdym razem, gdy w głowie mam jakiś w miarę poukładany plan, zaczynam pisać i się w nim gubię. Potem jestem zły na siebie za to, że nie przedstawiłem myśli w taki sposób, w jaki chciałem, bądź że o czymś zapomniałem, a następnie przez długi czas wpadam na pomysły, jak mogłem napisać coś dużo lepiej i drażni mnie to tak długo, aż zapomnę o problematycznym tekście. 

Dlatego do pisania bloga podchodziłem sceptycznie, a właściwie nawet nie podchodziłem, bo omijałem ten pomysł szerokim łukiem. Jednak jeżeli się do czegoś zobowiązuje, to należy się z tego wywiązywać. Gdy opisywałem w Planie Rozwoju - dokumencie, w którym jako kandydat na stypendystę opracowywałem plan osiągnięć na dany rok szkolny - pomysł utworzenia bloga o tematyce informatycznej, który miałby być skierowany do uczniów, wydawał się skuteczny, nietypowy, a przy tym nie taki trudny do zrealizowania. Czułem, że byłem gotów poświęcić regularnie małą ilość czasu na pisanie, zwłaszcza że mogłem to robić kiedy chcę i nie miałem wyznaczonych terminów publikacji. Tylko, jak zwykle z resztą, zabrakło mi systematyczności i staram się teraz przez ostatni miesiąc chodzenia do szkoły oraz wakacje nadrobić zaległości i opisać Wam jak najwięcej rzeczy ciekawych o nauce, informatyce i czymkolwiek, co znajdę.

*Bądźcie więc ode mnie mądrzejsi i nie zostawiajcie wszystkiego na ostatnią chwilę.*



_A przynajmniej tych większych, ważniejszych rzeczy_